// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx8hCYfWa5dYVI-vnI8yhkOwku_-Iy5qo',
    appId: '1:965888341728:web:13b3f158ec2a167c560285',
    messagingSenderId: '965888341728',
    projectId: 'sanjari-date',
    authDomain: 'sanjari-date.firebaseapp.com',
    storageBucket: 'sanjari-date.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_0vp829T6QxF0BKhXDM_LdpFLMQ70hBU',
    appId: '1:965888341728:android:c23dd84bd0903693560285',
    messagingSenderId: '965888341728',
    projectId: 'sanjari-date',
    storageBucket: 'sanjari-date.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsyFLEJVs8sBPV-jhqgM7NZX8HdwCc4wg',
    appId: '1:965888341728:ios:6200e82d77838476560285',
    messagingSenderId: '965888341728',
    projectId: 'sanjari-date',
    storageBucket: 'sanjari-date.firebasestorage.app',
    iosBundleId: 'com.sanjari.sanjari',
  );
}
