import { z } from 'zod';

export const appConfigSchema = z.object({
  NODE_ENV: z.enum(['development', 'test', 'staging', 'production']).default('development'),
  APP_PUBLIC_URL: z.url(),
  PORT: z.coerce.number().int().positive().default(4000),
  APP_NAME: z.string().default('Sanjari'),
  API_PUBLIC_URL: z.url(),
  ADMIN_PUBLIC_URL: z.url(),
  DATABASE_URL: z.string().min(1),
  REDIS_URL: z.string().min(1),
  JWT_ACCESS_SECRET: z.string().min(24),
  JWT_REFRESH_SECRET: z.string().min(24),
  S3_ENDPOINT: z.string().min(1),
  S3_PUBLIC_ENDPOINT: z.string().min(1),
  S3_REGION: z.string().min(1),
  S3_BUCKET: z.string().min(1),
  S3_ACCESS_KEY_ID: z.string().min(1),
  S3_SECRET_ACCESS_KEY: z.string().min(1),
  SMTP_HOST: z.string().min(1),
  SMTP_PORT: z.coerce.number().int().positive(),
  SMTP_FROM: z.email().default('support@sanjari.app'),
  SMS_PROVIDER: z.enum(['disabled', 'mailpit']).default('disabled'),
  SMS_DEV_INBOX: z.email().default('sms@sanjari.test'),
  PUSH_PROVIDER: z.enum(['disabled', 'local']).default('disabled'),
  ATTACHMENT_SCAN_PROVIDER: z.enum(['disabled', 'local']).default('disabled'),
  MODERATION_EVIDENCE_RETENTION_DAYS: z.coerce.number().int().positive().default(90),
  DATA_EXPORT_PROVIDER: z.enum(['disabled', 'local']).default('disabled'),
  ADMIN_MFA_PROVIDER: z.enum(['disabled', 'owner']).default('disabled'),
  PURCHASE_VERIFICATION_PROVIDER: z.enum(['disabled', 'local', 'owner']).default('disabled'),
  PURCHASE_WEBHOOK_SECRET: z.string().default(''),
  AUTH_TEST_CODE_VISIBILITY: z.coerce.boolean().default(false),
});
